# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e06e5fe7e8e35f2cf877deb4486613d89b8b7dddabf49d158a98cc03bdf33ddc6d9413d47bc1e31f16f2096961de7e693a601bafbd2b31a385866dc795b00425

test:
  secret_key_base: a26ba8d6a341198fcde2c247a37de2f45fde170cf9c0a115c2cad7988aa067f026c1dc88b33565c077815fca5fe6dc155775d96be4faba9f71b0a145d32ea467

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
