# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efd9152ffc2a2ec5c4499ef92a07bce2da9e2622a3dacc9e16fd7323ae8234ce9075f4fc3657efebb0fc6046220431a17f9404f200d5a8bf84736bcfdb774f7f

test:
  secret_key_base: b03a170c9a473eaa36bd988c7ea2e673650e22491bf0b9e61f4dc0801c0b4baa1af1a06bcec6384c9a3a4f815db02871abc8c585e4a737f8934856f534d383a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
